# This is a basic workflow to help you get started with Actions

name: CI / CD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the develop branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    name: Deploy to private server
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: SSH Remote Commands
      # You may pin to the exact commit or the version.
      # uses: appleboy/ssh-action@bf84735fa9986d048980965656d55112e863f432
      uses: appleboy/ssh-action@v0.1.3
      with:
        # ssh host
        host: ${{ secrets.host }}
        username: ubuntu
        key: ${{ secrets.key }}
        script: /home/ubuntu/scripts/update-bezier.sh
